name: Secret Scan (gitleaks)

on:
  pull_request:
    paths:
      - "**/*"
  workflow_call:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v3
        with:
          args: --report-format json --report-path gitleaks-report.json --redact
